### ISSUE TITLE
Accessibility Validation Issue

### ISSUE THREAD

**Issue by LauraWilson040** [LauraWilson040/saas-website#3]
MarkBot keeps asking for a focusable skip-link target. Am I missing a role besides the ones I already have? I tried adding a stand-alone skip-link earlier, but it didn't accept that either.

![Screen Shot 2020-04-22 at 9 43 09 PM](https://user-images.githubusercontent.com/55108851/80049924-4a2a8f80-84e2-11ea-9bdd-0025c0aa5e51.png)
![Screen Shot 2020-04-22 at 9 41 42 PM](https://user-images.githubusercontent.com/55108851/80049886-2a936700-84e2-11ea-970c-c07feac95e2a.png)

@muxlowc

**Comment by muxlowc** [comment]
@LauraWilson040  the text you have in your href="" should be the exact same as an id="".. so for example, you have href="#nav" in your skip-links, but your nav have an id of "navigation", so these don't match up. Also, I think you may be getting confused between roles and skip-links. - You dont need href="complementary" inyour skip-links 

roles= main parts of your site like your header ("banner") main ("main") footer ("contentinfo") etc. so that screenreaders can jump to these "landmarks" on a page easier. Whereas, skip-links, though similar, are a bit different - they allow someone who tabs through a page to easily skip to certain parts of a page (which are normally just "skip to nav"(`<nav>`) and "skip to main content"(`<main>`)

**Comment by LauraWilson040** [comment]
Thank you for the help! It worked. I'll be posting my Request for Grade shortly.
